name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "main"
  workflow_dispatch:   # ✅ 手動觸發按鈕

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove old config.json if exists
        run: rm -f public/config.json

      - name: Generate config.json
        run: |
          echo '{"host":"${{ secrets.API_HOST }}","frontendDomain":"${{ secrets.AGENT_ROUTE }}"}' > public/config.json

      - name: Show generated config.json
        run: cat public/config.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
